/**
 * Auto-generated file
 * Wed May 22 2024 20:34:57 GMT-0400 (Eastern Daylight Time)
 */

import Long from "long";
import { ValueOf } from "type-fest";

export type CMsgClientFriendMsg = {
	steamid?: Long
	chatEntryType?: number
	message?: Buffer
	rtime32ServerTimestamp?: number
	echoToSender?: boolean
}

export type CMsgClientFriendMsgIncoming = {
	steamidFrom?: Long
	chatEntryType?: number
	fromLimitedAccount?: boolean
	message?: Buffer
	rtime32ServerTimestamp?: number
}

export type CMsgClientAddFriend = {
	steamidToAdd?: Long
	accountnameOrEmailToAdd?: string
}

export type CMsgClientAddFriendResponse = {
	eresult?: number
	steamIdAdded?: Long
	personaNameAdded?: string
}

export type CMsgClientRemoveFriend = {
	friendid?: Long
}

export type CMsgClientHideFriend = {
	friendid?: Long
	hide?: boolean
}

export type CMsgClientFriendsList = {
	bincremental?: boolean
	friends?: .CMsgClientFriendsList.Friend[]
	maxFriendCount?: number
	activeFriendCount?: number
	friendsLimitHit?: boolean
}

export type CMsgClientFriendsGroupsList = {
	bremoval?: boolean
	bincremental?: boolean
	friendGroups?: .CMsgClientFriendsGroupsList.FriendGroup[]
	memberships?: .CMsgClientFriendsGroupsList.FriendGroupsMembership[]
}

export type CMsgClientPlayerNicknameList = {
	removal?: boolean
	incremental?: boolean
	nicknames?: .CMsgClientPlayerNicknameList.PlayerNickname[]
}

export type CMsgClientSetPlayerNickname = {
	steamid?: Long
	nickname?: string
}

export type CMsgClientSetPlayerNicknameResponse = {
	eresult?: number
}

export type CMsgClientRequestFriendData = {
	personaStateRequested?: number
	friends?: Long[]
}

export type CMsgClientChangeStatus = {
	personaState?: number
	playerName?: string
	isAutoGeneratedName?: boolean
	highPriority?: boolean
	personaSetByUser?: boolean
	personaStateFlags?: number
	needPersonaResponse?: boolean
	isClientIdle?: boolean
}

export type CMsgPersonaChangeResponse = {
	result?: number
	playerName?: string
}

export type CMsgClientPersonaState = {
	statusFlags?: number
	friends?: .CMsgClientPersonaState.Friend[]
}

export type CMsgClientFriendProfileInfo = {
	steamidFriend?: Long
}

export type CMsgClientFriendProfileInfoResponse = {
	eresult?: number
	steamidFriend?: Long
	timeCreated?: number
	realName?: string
	cityName?: string
	stateName?: string
	countryName?: string
	headline?: string
	summary?: string
}

export type CMsgClientCreateFriendsGroup = {
	steamid?: Long
	groupname?: string
	steamidFriends?: Long[]
}

export type CMsgClientCreateFriendsGroupResponse = {
	eresult?: number
	groupid?: number
}

export type CMsgClientDeleteFriendsGroup = {
	steamid?: Long
	groupid?: number
}

export type CMsgClientDeleteFriendsGroupResponse = {
	eresult?: number
}

export type CMsgClientManageFriendsGroup = {
	groupid?: number
	groupname?: string
	steamidFriendsAdded?: Long[]
	steamidFriendsRemoved?: Long[]
}

export type CMsgClientManageFriendsGroupResponse = {
	eresult?: number
}

export type CMsgClientAddFriendToGroup = {
	groupid?: number
	steamiduser?: Long
}

export type CMsgClientAddFriendToGroupResponse = {
	eresult?: number
}

export type CMsgClientRemoveFriendFromGroup = {
	groupid?: number
	steamiduser?: Long
}

export type CMsgClientRemoveFriendFromGroupResponse = {
	eresult?: number
}

export type CMsgClientGetEmoticonList = {
}

export type CMsgClientEmoticonList = {
	emoticons?: .CMsgClientEmoticonList.Emoticon[]
	stickers?: .CMsgClientEmoticonList.Sticker[]
	effects?: .CMsgClientEmoticonList.Effect[]
}

